<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $questionnaire->intitule }} - Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
        .header img {
            width: 100px;
        }
        .header h2 {
            font-size: 20px;
        }
        .content h3 {
            margin-bottom: 10px;
            font-size: 18px;
        }
        .chart-container {
            margin-bottom: 40px;
        }
        .chart-container img {
            width: 100%;
            max-width: 500px;
            height: auto;
        }
        .footer {
            position: absolute;
            bottom: 10px;
            width: 100%;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ asset('images/voiceup.png') }}" alt="VoiceUp Logo">
        <h2>{{ $questionnaire->entreprise->nom_entreprise }}</h2>
    </div>

    <h1>{{ $questionnaire->intitule }}</h1>
    <p>{{ $questionnaire->description }}</p>

    @foreach($data as $questionData)
    <div class="content">
        <h3>{{ $questionData['question'] }}</h3>
        @if($questionData['bar_chart'])
            <div class="chart-container">
                <img src="{{ $questionData['bar_chart'] }}" alt="Bar Chart">
            </div>
        @endif
        @if($questionData['doughnut_chart'])
            <div class="chart-container">
                <img src="{{ $questionData['doughnut_chart'] }}" alt="Doughnut Chart">
            </div>
        @endif
        @if($questionData['pie_chart'])
            <div class="chart-container">
                <img src="{{ $questionData['pie_chart'] }}" alt="Pie Chart">
            </div>
        @endif
    </div>
    @endforeach


    <div class="footer">
        <p>Generated by VoiceUp</p>
    </div>
</body>
</html>
