<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $questionnaire->intitule }} - Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            margin-bottom: 20px;
        }
        .header img {
            width: 100px;
        }
        .header h2 {
            font-size: 20px;
            margin: 0;
        }
        .content h3 {
            margin-bottom: 10px;
            font-size: 18px;
        }
        .chart-container img {
            width: 100%;
            max-width: 150px;
            height: auto;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <div class="header">
        <center> <img src="{{ public_path('images/voiceup.png') }}" alt="VoiceUp Logo" style="width: 100px;"></center>
        <h2>{{ $questionnaire->entreprise->nom_entreprise }}</h2>
    </div>

    <h1>{{ $questionnaire->intitule }}</h1>
    <p>{{ $questionnaire->description }}</p>

    @foreach($data as $questionData)
        <div class="content">
            <h3>{{ $questionData['question'] }}</h3>
            <table width="100%">
                <tr>
                    @if($questionData['bar_chart'])
                        <td align="center">
                            <div class="chart-container">
                                <img src="{{ $questionData['bar_chart'] }}" alt="Bar Chart">
                            </div>
                        </td>
                    @endif
                    @if($questionData['doughnut_chart'])
                        <td align="center">
                            <div class="chart-container">
                                <img src="{{ $questionData['doughnut_chart'] }}" alt="Doughnut Chart">
                            </div>
                        </td>
                    @endif
                    @if($questionData['pie_chart'])
                        <td align="center">
                            <div class="chart-container">
                                <img src="{{ $questionData['pie_chart'] }}" alt="Pie Chart">
                            </div>
                        </td>
                    @endif
                </tr>
            </table>
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by VoiceUp</p>
    </div>
</body>
</html>
